dirs        :=  . FitnessStrategies GenerationSizeStrategies MutationFactorStrategies MutationStrategies RandomStrategies SelectionStrategies Values

INC         = -I../selforg/include -I../selforg -I. -Iinclude -Iinclude/ga_tools
