#!/bin/bash
# Example usage of the cppcheck analysis script

echo "Cppcheck Analysis Examples for LPZRobots"
echo "========================================"
echo ""
echo "1. Quick analysis (faster, fewer checks):"
echo "   ./scripts/cppcheck_analysis.sh --quick"
echo ""
echo "2. Full analysis with incremental caching (default):"
echo "   ./scripts/cppcheck_analysis.sh"
echo ""
echo "3. Full analysis without caching (slower but thorough):"
echo "   ./scripts/cppcheck_analysis.sh --no-cache"
echo ""
echo "4. Generate HTML report for easy navigation:"
echo "   ./scripts/cppcheck_analysis.sh --html"
echo "   # Then open: build/cppcheck/reports/html/index.html"
echo ""
echo "5. Enable cross-translation unit analysis (very thorough but slow):"
echo "   ./scripts/cppcheck_analysis.sh --ctu"
echo ""
echo "6. Run with MISRA addon (if installed):"
echo "   ./scripts/cppcheck_analysis.sh --misra"
echo ""
echo "7. Run with multiple options:"
echo "   ./scripts/cppcheck_analysis.sh --html --ctu -j 8"
echo ""
echo "8. CI/CD integration example:"
echo "   # Returns exit code 0 if no errors, 1 if errors, 2 if warnings exceed threshold"
echo "   if ./scripts/cppcheck_analysis.sh --quick; then"
echo "     echo 'Static analysis passed!'"
echo "   else"
echo "     echo 'Static analysis failed!'"
echo "     exit 1"
echo "   fi"
echo ""
echo "View help for all options:"
echo "   ./scripts/cppcheck_analysis.sh --help"