# LPZRobots Core Configuration
# This is the main module that ties everything together

# Include all modules
include(${CMAKE_CURRENT_LIST_DIR}/LPZRobotsPlatform.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/LPZRobotsCompiler.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/LPZRobotsDependencies.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/LPZRobotsTargets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/LPZRobotsLibrary.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/LPZRobotsTesting.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/SimulationBuild.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/QtMacOSConfig.cmake)

# Main configuration function
function(lpzrobots_configure)
    # Detect platform
    lpzrobots_detect_platform()
    
    # Configure compiler
    lpzrobots_configure_compiler()
    
    # Apply global compiler settings
    add_compile_options(${LPZROBOTS_BASE_WARNINGS})
    add_compile_options(${LPZROBOTS_SUPPRESS_WARNINGS})
    
    if(DEFINED LPZROBOTS_GNU_WARNINGS)
        add_compile_options(${LPZROBOTS_GNU_WARNINGS})
    endif()
    
    # Find dependencies
    lpzrobots_find_dependencies()
    
    # Propagate dependency variables to parent scope
    set(LPZROBOTS_HAS_DOCTEST ${LPZROBOTS_HAS_DOCTEST} PARENT_SCOPE)
    
    # Set up installation directories
    include(GNUInstallDirs)
    set(LPZROBOTS_DATA_DIR "${CMAKE_INSTALL_DATADIR}/lpzrobots" PARENT_SCOPE)
    set(LPZROBOTS_EXAMPLES_DIR "${LPZROBOTS_DATA_DIR}/examples" PARENT_SCOPE)
    set(LPZROBOTS_SIMULATIONS_DIR "${LPZROBOTS_DATA_DIR}/simulations" PARENT_SCOPE)
    
    # Export configuration
    set(CMAKE_EXPORT_COMPILE_COMMANDS ON PARENT_SCOPE)
    
    # Create version file
    file(WRITE "${CMAKE_BINARY_DIR}/VERSION.txt" "${PROJECT_VERSION}")
endfunction()

# Function to print configuration summary
function(lpzrobots_print_summary)
    message(STATUS "")
    message(STATUS "LPZRobots ${PROJECT_VERSION} Configuration Summary")
    message(STATUS "=====================================")
    message(STATUS "Platform:          ${LPZROBOTS_PLATFORM}")
    message(STATUS "Build type:        ${CMAKE_BUILD_TYPE}")
    message(STATUS "C++ Standard:      ${CMAKE_CXX_STANDARD}")
    message(STATUS "Compiler:          ${LPZROBOTS_COMPILER_ID} ${LPZROBOTS_COMPILER_VERSION}")
    message(STATUS "")
    message(STATUS "Options:")
    message(STATUS "  Shared libs:     ${BUILD_SHARED_LIBS}")
    message(STATUS "  Examples:        ${BUILD_EXAMPLES}")
    message(STATUS "  Tests:           ${BUILD_TESTS}")
    message(STATUS "  GUI tools:       ${BUILD_GUI_TOOLS}")
    message(STATUS "  Java tools:      ${BUILD_JAVA_TOOLS}")
    message(STATUS "  SIMD:            ${ENABLE_SIMD}")
    message(STATUS "  OpenMP:          ${ENABLE_OPENMP}")
    message(STATUS "  System ODE:      ${LPZROBOTS_USE_SYSTEM_ODE}")
    message(STATUS "  Install type:    ${LPZROBOTS_INSTALL_TYPE}")
    message(STATUS "  Opt libraries:   ${BUILD_OPT_LIBRARIES}")
    message(STATUS "  Debug libraries: ${BUILD_DBG_LIBRARIES}")
    
    lpzrobots_print_dependencies()
    
    message(STATUS "Install prefix:    ${CMAKE_INSTALL_PREFIX}")
    message(STATUS "=====================================")
    message(STATUS "")
    
    # Build instructions
    if(CMAKE_GENERATOR MATCHES "Make")
        message(STATUS "To build: make -j${CMAKE_BUILD_PARALLEL_LEVEL}")
        message(STATUS "To install: make install")
    else()
        message(STATUS "To build: cmake --build . -j${CMAKE_BUILD_PARALLEL_LEVEL}")
        message(STATUS "To install: cmake --install .")
    endif()
    
    message(STATUS "")
    
    # Development mode notes
    if(LPZROBOTS_INSTALL_TYPE STREQUAL "DEVEL")
        message(STATUS "DEVEL Mode Notes:")
        message(STATUS "  - Libraries remain in source tree")
        message(STATUS "  - Only utilities and config scripts are installed")
        message(STATUS "  - Use *-config scripts to find libraries")
        message(STATUS "  - Simulations will use relative paths")
    endif()
    
    message(STATUS "=====================================")
endfunction()

# Function to setup component build order
function(lpzrobots_add_components)
    # Core libraries in dependency order
    if(EXISTS "${CMAKE_SOURCE_DIR}/selforg/CMakeLists.txt")
        add_subdirectory(selforg)
        # Config script is generated by lpzrobots_add_component_library
    endif()
    
    # ODE handling
    if(NOT LPZROBOTS_USE_SYSTEM_ODE)
        if(EXISTS "${CMAKE_SOURCE_DIR}/include/ode-dbl/CMakeLists.txt")
            add_subdirectory(include/ode-dbl)
        endif()
    endif()
    # Generate ode-dbl-config script (for compatibility)
    # This is not a component library, so we generate it here
    lpzrobots_generate_config_script(ode-dbl)
    
    # Configurator before ode_robots if GUI tools enabled
    if(BUILD_GUI_TOOLS AND EXISTS "${CMAKE_SOURCE_DIR}/configurator/CMakeLists.txt")
        add_subdirectory(configurator)
        # Config script is generated by lpzrobots_add_component_library
    endif()
    
    # ode_robots after selforg and configurator
    if(EXISTS "${CMAKE_SOURCE_DIR}/ode_robots/CMakeLists.txt")
        add_subdirectory(ode_robots)
        # Config script is generated by lpzrobots_add_component_library
    endif()
    
    # ga_tools
    if(EXISTS "${CMAKE_SOURCE_DIR}/ga_tools/CMakeLists.txt")
        add_subdirectory(ga_tools)
        # Config script is generated by lpzrobots_add_component_library
    endif()
    
    # GUI tools (except configurator which was already added)
    if(BUILD_GUI_TOOLS)
        if(EXISTS "${CMAKE_SOURCE_DIR}/guilogger/CMakeLists.txt")
            add_subdirectory(guilogger)
        endif()
        
        if(EXISTS "${CMAKE_SOURCE_DIR}/matrixviz/CMakeLists.txt")
            add_subdirectory(matrixviz)
        endif()
    endif()
    
    # Java tools
    if(BUILD_JAVA_TOOLS AND LPZROBOTS_HAS_JAVA)
        lpzrobots_build_java_tools()
    endif()
    
    # Optional components
    if(EXISTS "${CMAKE_SOURCE_DIR}/ecbrobots/CMakeLists.txt")
        add_subdirectory(ecbrobots)
    endif()
    
    if(EXISTS "${CMAKE_SOURCE_DIR}/real_robots/CMakeLists.txt")
        add_subdirectory(real_robots)
    endif()
    
    # Tests
    if(BUILD_TESTS)
        enable_testing()
        if(EXISTS "${CMAKE_SOURCE_DIR}/tests/CMakeLists.txt")
            add_subdirectory(tests)
        endif()
    endif()
    
    # Note: Examples and simulations are handled by individual component CMakeLists.txt files
    # to avoid duplicate binary directory errors
endfunction()

# Function to build Java tools
function(lpzrobots_build_java_tools)
    include(UseJava)
    
    # Soundman
    if(EXISTS "${CMAKE_SOURCE_DIR}/soundman/src")
        file(GLOB SOUNDMAN_JAVA_SOURCES soundman/src/*.java)
        
        if(SOUNDMAN_JAVA_SOURCES)
            file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/soundman/class)
            file(MAKE_DIRECTORY ${CMAKE_BINARY_DIR}/soundman/bin)
            
            add_custom_target(soundman ALL
                COMMAND ${Java_JAVAC_EXECUTABLE} -d ${CMAKE_BINARY_DIR}/soundman/class ${SOUNDMAN_JAVA_SOURCES}
                WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
                COMMENT "Building soundman Java classes"
            )
            
            # Install soundman
            install(DIRECTORY ${CMAKE_BINARY_DIR}/soundman/class/
                DESTINATION ${CMAKE_INSTALL_LIBDIR}/soundMan
                FILES_MATCHING PATTERN "*.class"
            )
            
            # Configure and install script
            if(EXISTS ${CMAKE_SOURCE_DIR}/soundman/bin/soundMan)
                configure_file(
                    ${CMAKE_SOURCE_DIR}/soundman/bin/soundMan
                    ${CMAKE_BINARY_DIR}/soundman/bin/soundMan
                    @ONLY
                )
                
                install(PROGRAMS ${CMAKE_BINARY_DIR}/soundman/bin/soundMan
                    DESTINATION ${CMAKE_INSTALL_BINDIR}
                )
            endif()
        endif()
    endif()
    
    # Java controller
    if(EXISTS "${CMAKE_SOURCE_DIR}/javacontroller/src")
        file(GLOB_RECURSE JAVACONTROLLER_SOURCES javacontroller/src/*.java)
        file(GLOB_RECURSE JAVACONTROLLER_XJAVA javacontroller/src/*.xjava)
        
        # Process .xjava files
        set(JAVACONTROLLER_GENERATED)
        foreach(xjava_file ${JAVACONTROLLER_XJAVA})
            get_filename_component(xjava_name ${xjava_file} NAME_WE)
            set(java_file "${CMAKE_BINARY_DIR}/javacontroller/src/${xjava_name}.java")
            
            add_custom_command(
                OUTPUT ${java_file}
                COMMAND ${CMAKE_COMMAND} -E make_directory ${CMAKE_BINARY_DIR}/javacontroller/src
                COMMAND sed -e "s|PREFIX|${CMAKE_INSTALL_PREFIX}|g" ${xjava_file} > ${java_file}
                DEPENDS ${xjava_file}
                COMMENT "Processing ${xjava_file}"
            )
            list(APPEND JAVACONTROLLER_GENERATED ${java_file})
        endforeach()
        
        if(JAVACONTROLLER_SOURCES OR JAVACONTROLLER_GENERATED)
            set(ALL_JAVA_SOURCES ${JAVACONTROLLER_SOURCES} ${JAVACONTROLLER_GENERATED})
            
            # Check for manifest
            set(MANIFEST_FILE)
            if(EXISTS ${CMAKE_SOURCE_DIR}/javacontroller/src/ManifestMain)
                set(MANIFEST_FILE ${CMAKE_SOURCE_DIR}/javacontroller/src/ManifestMain)
            endif()
            
            if(MANIFEST_FILE)
                add_jar(javacontroller
                    SOURCES ${ALL_JAVA_SOURCES}
                    MANIFEST ${MANIFEST_FILE}
                    OUTPUT_DIR ${CMAKE_BINARY_DIR}/javacontroller
                )
            else()
                add_jar(javacontroller
                    SOURCES ${ALL_JAVA_SOURCES}
                    OUTPUT_DIR ${CMAKE_BINARY_DIR}/javacontroller
                )
            endif()
            
            install_jar(javacontroller DESTINATION ${CMAKE_INSTALL_LIBDIR})
        endif()
    endif()
endfunction()

# Function to setup package configuration
function(lpzrobots_setup_package)
    include(CMakePackageConfigHelpers)
    
    # Generate config file
    configure_package_config_file(
        "${CMAKE_SOURCE_DIR}/cmake/LPZRobotsConfig.cmake.in"
        "${CMAKE_BINARY_DIR}/lpzrobotsConfig.cmake"
        INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/lpzrobots
    )
    
    # Create version file
    write_basic_package_version_file(
        "${CMAKE_BINARY_DIR}/lpzrobotsConfigVersion.cmake"
        VERSION ${PROJECT_VERSION}
        COMPATIBILITY SameMajorVersion
    )
    
    # Install package configuration
    install(
        FILES
        "${CMAKE_BINARY_DIR}/lpzrobotsConfig.cmake"
        "${CMAKE_BINARY_DIR}/lpzrobotsConfigVersion.cmake"
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/lpzrobots
    )
    
    # Install all CMake modules
    install(
        DIRECTORY ${CMAKE_SOURCE_DIR}/cmake/
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/lpzrobots
        FILES_MATCHING PATTERN "*.cmake"
    )
    
    # Export targets
    install(EXPORT LPZRobotsTargets
        FILE LPZRobotsTargets.cmake
        NAMESPACE lpzrobots::
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/lpzrobots
    )
    
    # Export for build tree
    export(EXPORT LPZRobotsTargets
        FILE "${CMAKE_BINARY_DIR}/LPZRobotsTargets.cmake"
        NAMESPACE lpzrobots::
    )
    
    # Install version file
    install(
        FILES "${CMAKE_BINARY_DIR}/VERSION.txt"
        DESTINATION ${LPZROBOTS_DATA_DIR}
    )
endfunction()

# Function to setup CPack
function(lpzrobots_setup_cpack)
    # CPack configuration
    set(CPACK_PACKAGE_NAME "lpzrobots")
    set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
    set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A versatile simulator for robotic research on self-organization of behavior")
    set(CPACK_PACKAGE_VENDOR "Leipzig Robot Group")
    set(CPACK_PACKAGE_CONTACT "martius@informatik.uni-leipzig.de")
    set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE")
    set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
    
    if(APPLE)
        set(CPACK_GENERATOR "DragNDrop;TGZ")
        set(CPACK_DMG_VOLUME_NAME "LPZRobots ${PROJECT_VERSION}")
        if(EXISTS "${CMAKE_SOURCE_DIR}/doc/images/dmg-background.png")
            set(CPACK_DMG_BACKGROUND_IMAGE "${CMAKE_SOURCE_DIR}/doc/images/dmg-background.png")
        endif()
    elseif(UNIX)
        set(CPACK_GENERATOR "TGZ;DEB;RPM")
        set(CPACK_DEBIAN_PACKAGE_DEPENDS "libqt6-dev, libgsl-dev, libopenscenegraph-dev")
        set(CPACK_RPM_PACKAGE_REQUIRES "qt6-devel, gsl-devel, OpenSceneGraph-devel")
    endif()
    
    include(CPack)
endfunction()

# Function to print configuration summary
function(lpzrobots_print_summary)
    message(STATUS "")
    message(STATUS "===== LPZRobots Configuration Summary =====")
    message(STATUS "Version:              ${PROJECT_VERSION}")
    message(STATUS "Install prefix:       ${CMAKE_INSTALL_PREFIX}")
    message(STATUS "Install type:         ${LPZROBOTS_INSTALL_TYPE}")
    message(STATUS "Build type:           ${CMAKE_BUILD_TYPE}")
    
    message(STATUS "")
    message(STATUS "Compiler:")
    message(STATUS "  C++ Compiler:       ${CMAKE_CXX_COMPILER}")
    message(STATUS "  C++ Standard:       C++${CMAKE_CXX_STANDARD}")
    message(STATUS "  Compiler ID:        ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
    if(APPLE)
        message(STATUS "  Architecture:       ${CMAKE_OSX_ARCHITECTURES}")
    endif()
    
    message(STATUS "")
    message(STATUS "Build Options:")
    message(STATUS "  Shared libraries:   ${BUILD_SHARED_LIBS}")
    message(STATUS "  Examples:           ${BUILD_EXAMPLES}")
    message(STATUS "  Unit tests:         ${BUILD_TESTS}")
    message(STATUS "  GUI tools:          ${BUILD_GUI_TOOLS}")
    message(STATUS "  Java tools:         ${BUILD_JAVA_TOOLS}")
    message(STATUS "  SIMD:               ${ENABLE_SIMD}")
    message(STATUS "  OpenMP:             ${ENABLE_OPENMP}")
    message(STATUS "  Legacy variants:    ${LPZROBOTS_LEGACY_VARIANTS}")
    
    message(STATUS "")
    message(STATUS "Dependencies:")
    lpzrobots_print_dependencies()
    
    # Print sanitizer configuration if enabled
    if(LPZROBOTS_ENABLE_SANITIZERS)
        message(STATUS "")
        message(STATUS "Sanitizers:")
        message(STATUS "  AddressSanitizer:   ${LPZROBOTS_SANITIZER_ADDRESS}")
        message(STATUS "  ThreadSanitizer:    ${LPZROBOTS_SANITIZER_THREAD}")
        message(STATUS "  UBSanitizer:        ${LPZROBOTS_SANITIZER_UNDEFINED}")
        message(STATUS "  MemorySanitizer:    ${LPZROBOTS_SANITIZER_MEMORY}")
    endif()
    
    # Print static analysis configuration
    if(LPZROBOTS_ENABLE_CLANG_TIDY OR LPZROBOTS_ENABLE_CPPCHECK OR LPZROBOTS_ENABLE_IWYU)
        message(STATUS "")
        message(STATUS "Static Analysis:")
        message(STATUS "  clang-tidy:         ${LPZROBOTS_ENABLE_CLANG_TIDY}")
        message(STATUS "  cppcheck:           ${LPZROBOTS_ENABLE_CPPCHECK}")
        message(STATUS "  include-what-you-use: ${LPZROBOTS_ENABLE_IWYU}")
    endif()
    
    # Print coverage configuration
    if(LPZROBOTS_ENABLE_COVERAGE)
        message(STATUS "")
        message(STATUS "Code Coverage:        ENABLED")
    endif()
    
    message(STATUS "")
    message(STATUS "Components to build:")
    if(TARGET selforg)
        message(STATUS "  selforg            (controller library)")
    endif()
    if(TARGET ode_robots)
        message(STATUS "  ode_robots         (robot simulation library)")
    endif()
    if(TARGET ga_tools)
        message(STATUS "  ga_tools           (genetic algorithm tools)")
    endif()
    if(TARGET configurator)
        message(STATUS "  configurator       (runtime configuration tool)")
    endif()
    if(TARGET guilogger)
        message(STATUS "  guilogger          (data visualization)")
    endif()
    if(TARGET matrixviz)
        message(STATUS "  matrixviz          (matrix visualization)")
    endif()
    
    message(STATUS "=========================================")
    message(STATUS "")
endfunction()